# Generated by Django 3.2 on 2022-03-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pre_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pre sale price'),
        ),
    ]
